// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoUnip.Models;

#nullable disable

namespace ProjetoUnip.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoUnip.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numero");

                    b.HasKey("Id");

                    b.ToTable("Tb_Endereco");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("CPF")
                        .HasColumnType("bigint")
                        .HasColumnName("CPF");

                    b.Property<int>("Id_Endereco")
                        .HasColumnType("int");

                    b.Property<int>("Id_Telefone")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Id_Endereco");

                    b.HasIndex("Id_Telefone");

                    b.ToTable("tb_Pessoa");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DDD")
                        .HasColumnType("int")
                        .HasColumnName("DDD");

                    b.Property<int>("Id_FKTipoTelefone")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDeTelefone")
                        .HasColumnType("int")
                        .HasColumnName("NumeroDeTelefone");

                    b.HasKey("Id");

                    b.HasIndex("Id_FKTipoTelefone");

                    b.ToTable("Tb_Telefone");
                });

            modelBuilder.Entity("ProjetoUnip.Models.TipoTelefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Tb_TipoTelefone");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Pessoa", b =>
                {
                    b.HasOne("ProjetoUnip.Models.Endereco", "Endereco")
                        .WithMany("Pessoas")
                        .HasForeignKey("Id_Endereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoasEndereco");

                    b.HasOne("ProjetoUnip.Models.Telefone", "Telefone")
                        .WithMany("Pessoas")
                        .HasForeignKey("Id_Telefone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoasTelefone");

                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Telefone", b =>
                {
                    b.HasOne("ProjetoUnip.Models.TipoTelefone", "TipoTelefone")
                        .WithMany("Telefones")
                        .HasForeignKey("Id_FKTipoTelefone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TelefoneTipoTelefone");

                    b.Navigation("TipoTelefone");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Endereco", b =>
                {
                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("ProjetoUnip.Models.Telefone", b =>
                {
                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("ProjetoUnip.Models.TipoTelefone", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
